### ISSUE TITLE
Replace TimeMarker type in DataTypes.h with something from std::chrono.

### ISSUE THREAD

**Issue by MakoEnergy** [BlackToppStudios/Mezz_StaticFoundation#60]
Post C++11 we should be using std::chrono for most our timing needs, with very few exceptions.  We could keep this type around by renaming it "OldTimeMarker" or "LegacyTimeMarker".  But regardless a default time marking type in the Mezzanine should be something from std::chrono.

**Comment by Sqeaky** [comment]
This is fixed as of now. New code looks like this:

    /// @brief A datatype used to indicate a specific point in time, or a timestamp.
    /// @details This is made into its own datatype for when we want to tweak the possible size for a timestamp.
    typedef UInt32 OldTimeMarker;

    /// @brief A datatype for precision timing with std::chrono.
    /// @details This is a time point with the standard high resolution clock which can be used for frame timings.
    typedef std::chrono::time_point<std::chrono::high_resolution_clock> PrecisionTimeMarker;
